// Kategorien-Icons: categories.icon enthält lucide-Namen in kebab-case.
// Statisches Mapping (kein dynamic import aller Icons) — deckt die Seed-Daten
// aus supabase/migrations/0002_seed.sql plus gängige Varianten ab.
import {
  Armchair,
  Bed,
  BedDouble,
  Calculator,
  Car,
  Coffee,
  Droplets,
  GraduationCap,
  Hammer,
  Home,
  Laptop,
  PartyPopper,
  Scale,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smile,
  Sparkles,
  Stethoscope,
  Store,
  Thermometer,
  Tractor,
  Truck,
  Utensils,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

const CATEGORY_ICONS: Record<string, LucideIcon> = {
  armchair: Armchair,
  bed: Bed,
  "bed-double": BedDouble,
  calculator: Calculator,
  car: Car,
  coffee: Coffee,
  droplets: Droplets,
  "graduation-cap": GraduationCap,
  hammer: Hammer,
  home: Home,
  laptop: Laptop,
  "party-popper": PartyPopper,
  scale: Scale,
  scissors: Scissors,
  shield: Shield,
  shirt: Shirt,
  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  smile: Smile,
  sparkles: Sparkles,
  stethoscope: Stethoscope,
  store: Store,
  thermometer: Thermometer,
  tractor: Tractor,
  truck: Truck,
  utensils: Utensils,
  wrench: Wrench,
  zap: Zap,
};

export function categoryIcon(name: string | null | undefined): LucideIcon {
  return (name && CATEGORY_ICONS[name]) || Store;
}
