-- Stammdaten: 38 Gemeinden des Kosovo + Start-Kategorien

insert into public.cities (slug, name_sq, name_sr, name_en, name_de) values
  ('prishtina',      'Prishtinë',      'Priština',            'Pristina',        'Pristina'),
  ('prizren',        'Prizren',        'Prizren',             'Prizren',         'Prizren'),
  ('peja',           'Pejë',           'Peć',                 'Peja',            'Peja'),
  ('gjakova',        'Gjakovë',        'Đakovica',            'Gjakova',         'Gjakova'),
  ('mitrovica',      'Mitrovicë',      'Kosovska Mitrovica',  'Mitrovica',       'Mitrovica'),
  ('mitrovica-veriore', 'Mitrovicë e Veriut', 'Severna Mitrovica', 'North Mitrovica', 'Nord-Mitrovica'),
  ('ferizaj',        'Ferizaj',        'Uroševac',            'Ferizaj',         'Ferizaj'),
  ('gjilan',         'Gjilan',         'Gnjilane',            'Gjilan',          'Gjilan'),
  ('podujeva',       'Podujevë',       'Podujevo',            'Podujeva',        'Podujeva'),
  ('vushtrri',       'Vushtrri',       'Vučitrn',             'Vushtrri',        'Vushtrri'),
  ('suhareka',       'Suharekë',       'Suva Reka',           'Suhareka',        'Suhareka'),
  ('rahovec',        'Rahovec',        'Orahovac',            'Rahovec',         'Rahovec'),
  ('drenas',         'Drenas',         'Glogovac',            'Drenas',          'Drenas'),
  ('lipjan',         'Lipjan',         'Lipljan',             'Lipjan',          'Lipjan'),
  ('malisheva',      'Malishevë',      'Mališevo',            'Malisheva',       'Malisheva'),
  ('kamenica',       'Kamenicë',       'Kosovska Kamenica',   'Kamenica',        'Kamenica'),
  ('viti',           'Viti',           'Vitina',              'Viti',            'Viti'),
  ('decan',          'Deçan',          'Dečani',              'Decan',           'Decan'),
  ('istog',          'Istog',          'Istok',               'Istog',           'Istog'),
  ('klina',          'Klinë',          'Klina',               'Klina',           'Klina'),
  ('skenderaj',      'Skenderaj',      'Srbica',              'Skenderaj',       'Skenderaj'),
  ('dragash',        'Dragash',        'Dragaš',              'Dragash',         'Dragash'),
  ('fushe-kosova',   'Fushë Kosovë',   'Kosovo Polje',        'Fushe Kosova',    'Fushe Kosova'),
  ('kacanik',        'Kaçanik',        'Kačanik',             'Kacanik',         'Kacanik'),
  ('shtime',         'Shtime',         'Štimlje',             'Shtime',          'Shtime'),
  ('obiliq',         'Obiliq',         'Obilić',              'Obiliq',          'Obiliq'),
  ('junik',          'Junik',          'Junik',               'Junik',           'Junik'),
  ('hani-i-elezit',  'Hani i Elezit',  'Elez Han',            'Hani i Elezit',   'Hani i Elezit'),
  ('mamusha',        'Mamushë',        'Mamuša',              'Mamusha',         'Mamusha'),
  ('gracanica',      'Graçanicë',      'Gračanica',           'Gracanica',       'Gracanica'),
  ('ranillug',       'Ranillug',       'Ranilug',             'Ranillug',        'Ranillug'),
  ('partesh',        'Partesh',        'Parteš',              'Partesh',         'Partesh'),
  ('kllokot',        'Kllokot',        'Klokot',              'Kllokot',         'Kllokot'),
  ('novoberda',      'Novobërdë',      'Novo Brdo',           'Novoberda',       'Novoberda'),
  ('shterpca',       'Shtërpcë',       'Štrpce',              'Shterpca',        'Shterpca'),
  ('zubin-potok',    'Zubin Potok',    'Zubin Potok',         'Zubin Potok',     'Zubin Potok'),
  ('zvecan',         'Zveçan',         'Zvečan',              'Zvecan',          'Zvecan'),
  ('leposaviq',      'Leposaviq',      'Leposavić',           'Leposaviq',       'Leposaviq');

insert into public.categories (slug, name_sq, name_de, name_en, name_sr, icon, sort) values
  ('ndertim',           'Ndërtim & Renovim',      'Bau & Renovierung',       'Construction & Renovation', 'Građevina i renoviranje',  'hammer',        1),
  ('elektricist',       'Elektricist',            'Elektriker',              'Electrician',               'Električar',               'zap',           2),
  ('hidraulik',         'Hidraulik',              'Klempner / Sanitär',      'Plumber',                   'Vodoinstalater',           'droplets',      3),
  ('klima-ngrohje',     'Klimë & Ngrohje',        'Klima & Heizung',         'AC & Heating',              'Klima i grejanje',         'thermometer',   4),
  ('auto-servis',       'Auto Servis',            'Autowerkstatt',           'Car Repair',                'Auto servis',              'car',           5),
  ('pastrim',           'Pastrim',                'Reinigung',               'Cleaning',                  'Čišćenje',                 'sparkles',      6),
  ('mobileri',          'Mobileri & Dizajn',      'Möbel & Einrichtung',     'Furniture & Interior',      'Nameštaj i enterijer',     'armchair',      7),
  ('transport',         'Transport & Logjistikë', 'Transport & Logistik',    'Transport & Logistics',     'Prevoz i logistika',       'truck',         8),
  ('restorant',         'Restorant',              'Restaurant',              'Restaurant',                'Restoran',                 'utensils',      9),
  ('kafene',            'Kafene & Ëmbëltore',     'Café & Konditorei',       'Café & Pastry',             'Kafić i poslastičarnica',  'coffee',       10),
  ('hotel',             'Hotel & Bujtinë',        'Hotel & Unterkunft',      'Hotel & Accommodation',     'Hotel i smeštaj',          'bed',          11),
  ('bukuri',            'Floktore & Bukuri',      'Friseur & Kosmetik',      'Hair & Beauty',             'Frizer i lepota',          'scissors',     12),
  ('shendetesi',        'Shëndetësi',             'Gesundheit',              'Health',                    'Zdravlje',                 'stethoscope',  13),
  ('stomatolog',        'Stomatolog',             'Zahnarzt',                'Dentist',                   'Zubar',                    'smile',        14),
  ('avokat',            'Avokat & Noter',         'Anwalt & Notar',          'Lawyer & Notary',           'Advokat i notar',          'scale',        15),
  ('kontabilitet',      'Kontabilitet',           'Buchhaltung',             'Accounting',                'Računovodstvo',            'calculator',   16),
  ('patundshmeri',      'Patundshmëri',           'Immobilien',              'Real Estate',               'Nekretnine',               'home',         17),
  ('teknologji',        'IT & Elektronikë',       'IT & Elektronik',         'IT & Electronics',          'IT i elektronika',         'laptop',       18),
  ('shitore',           'Shitore & Ushqimore',    'Läden & Lebensmittel',    'Shops & Groceries',         'Prodavnice i namirnice',   'shopping-cart',19),
  ('mode',              'Modë & Veshje',          'Mode & Bekleidung',       'Fashion & Clothing',        'Moda i odeća',             'shirt',        20),
  ('evente',            'Evente & Dasma',         'Events & Hochzeiten',     'Events & Weddings',         'Događaji i svadbe',        'party-popper', 21),
  ('edukim',            'Edukim & Kurse',         'Bildung & Kurse',         'Education & Courses',       'Obrazovanje i kursevi',    'graduation-cap',22),
  ('bujqesi',           'Bujqësi',                'Landwirtschaft',          'Agriculture',               'Poljoprivreda',            'tractor',      23),
  ('sigurime-financa',  'Sigurime & Financa',     'Versicherung & Finanzen', 'Insurance & Finance',       'Osiguranje i finansije',   'shield',       24);
